import { z } from 'zod/v4';

export enum TokenStatus {
  UNAUTHORIZED = 'UNAUTHORIZED',

  ACCESS_TOKEN_VALID = 'ACCESS_TOKEN_VALID',
  ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
  ACCESS_TOKEN_INVALID = 'ACCESS_TOKEN_INVALID',
  ACCESS_TOKEN_MISSING = 'ACCESS_TOKEN_MISSING',

  REFRESH_TOKEN_VALID = 'REFRESH_TOKEN_VALID',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_MISSING = 'REFRESH_TOKEN_MISSING',
}

export const zTokenStatus = z.enum(TokenStatus);

export enum authResponse {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PASSWORD_INCORRECT = 'PASSWORD_INCORRECT',
  BAD_REQUEST = 'BAD_REQUEST',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS'
}

export const zAuthResponse = z.enum(authResponse);
